# Written by Richard Christopher, Copyright 2026 NeoTec, LLC
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "yfi-fuzz"
description = "libFuzzer targets for the Yamlfication parser."
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
yfi-syntax = { path = "../crates/yfi-syntax" }

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_utf8"
path = "fuzz_targets/parse_utf8.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_yfy"
path = "fuzz_targets/parse_yfy.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
